version: '3.9'

services:
  currency-exchange:
    image: amandockerhub/msv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network  


networks:
  currency-network:      