version: '3.9'

services:
  currency-exchange:
    image: amandockerhub/msv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
          
  currency-converter:
    image: amandockerhub/msv2-currency-converter-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq      
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  api-gateway:
    image: amandockerhub/msv2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq      
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  naming-server:
    image: amandockerhub/msv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

#docker run -p 9411:9411 openzipkin/zipkin:2.23 now lets add a service for to launch zipkin from docker-compose
#below config is defaulted in the MS so we have to configure this for containers to log request to zipkin server
#spring.zipkin.baseUrl=http://localhost:9411/
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq        
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart : always      # restart the container if it fails to run

  rabbitmq:
    image: rabbitmq:3.8.12-management #earlier, this image rabbitmq:3.5.3-management was giving exception in starting     
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network:      